Feature/start page
attech-org/zabava.game pull request #6
Opened 2022-12-08 18:19 UTC by ArtemLigerko

![WM-Screenshots-20221208201537](https://user-images.githubusercontent.com/103952847/206534336-3dc710bd-102c-42c7-b9df-ba97d9760137.png)

![WM-Screenshots-20221208201549](https://user-images.githubusercontent.com/103952847/206534403-6492eb26-823b-40a9-950d-7ec388a1e16e.png)

![WM-Screenshots-20221208201601](https://user-images.githubusercontent.com/103952847/206534435-c982d6dc-d621-475e-83a9-ff9746c5f57f.png)

2022-12-08 18:22 UTC, ArtemLigerko commented
The problem with <wired-input> is left, it`s not working with useState, I`m didn`t find solution and temporary used <input>

2022-12-08 20:34 UTC, alexandrtovmach requested changes

2022-12-08 20:34 UTC, alexandrtovmach commented on src/components/CreateGameForm.tsx
> +          <p>
not sure about using any wrapper here at all, but if you need it, then it shouldn't be a paragraph, maybe div?

2022-12-08 20:34 UTC, alexandrtovmach commented on src/components/CreateGameForm.tsx
> +  p {
if you agreed to use styled components, then you should avoid using nested styles, and create separate component for each element

2022-12-08 20:34 UTC, alexandrtovmach commented on src/wired.d.ts
>  declare namespace JSX {
please revert changes in this file, looks strange

2022-12-09 16:12 UTC, alexandrtovmach approved these changes

2022-12-09 16:12 UTC, merged